DEV=true
API_URL=https://flbygwtoslnwzjpqkbpp.supabase.co
API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsYnlnd3Rvc2xud3pqcHFrYnBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTQ3MjIzMTQsImV4cCI6MjAxMDI5ODMxNH0.PGZe9-2QtFtdw0zdZaU94XtgVpzsUNlAoWSVvcKZZu0
